### ISSUE TITLE
Make form work

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#1]
It looks like we're ready to make the form store data in the db

Let me know what if anything you need from me

**Comment by nivshah** [comment]
Thought about this for too long. Gonna make a Customer model that will allow us to store all the info visitors give us into a simple DB record.

**Comment by nivshah** [comment]
This is blocked by #12

**Comment by JFuller3000** [comment]
calling this closed: both forms store things in the db, any more nuanced issues can go in new bugs
