### ISSUE TITLE
verify moka in g-suite

### ISSUE THREAD

**Issue by darthsmall** [ElCinco/moka#10]

**Comment by nivshah** [comment]
this is not what i'd considered "opening an issue"

**Comment by darthsmall** [comment]
what kind of info would you like?

**Comment by darthsmall** [comment]
gandi verification worked today

**Comment by nivshah** [comment]
Yeah I looked up how to do it.

**Comment by nivshah** [comment]
Add MX records:


1 | 2
-- | --
ASPMX.L.GOOGLE.COM. | 1
ALT1.ASPMX.L.GOOGLE.COM. | 5
ALT2.ASPMX.L.GOOGLE.COM. | 5
ASPMX2.GOOGLEMAIL.COM. | 10
ASPMX3.GOOGLEMAIL.COM. | 10

**Comment by darthsmall** [comment]
ty ty

**Comment by nivshah** [comment]
donezo
