### ISSUE TITLE
finalize the minimum viable form UI/UX for the first round of ads

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#12]
Form UI/UX to finalize, so it can get built

- [ ] # of forms
- [ ] Fields
- [ ] Input Types

**# of forms**
One or two? If we switch to 1 form what is the form's new singular purpose? 

**Fields**
Current 1st form
- age
- gender
- state
- tobacco use
- contact preference

Current 2nd form
- name 
- weight
- kids
- income range
- overall health
- have a policy?

**Input Types**
Right now they are mad-lib style, so other than email, contact preference and overall health all the fields are <select> tags(dropdowns) for speed and simplicity's sake.
To me it's fine for v1 with all selects, but if y'all feel strongly we can totally blow that out some more, but bear in mind customizing form inputs is a pain in the ass because they're super hardcoded into browsers in a multitude of ways, so it takes some work/time.

**Comment by darthsmall** [comment]
we need to add
I need _250,000_ in coverage
$250,000, $500,000, $750,000 and $1,000,000

and only have VA and MD in the State dropdown
