### ISSUE TITLE
Spin up a mailchimp account

### ISSUE THREAD

**Issue by nivshah** [ElCinco/moka#14]
Create a mailchimp account. Share API access details here so we can send emails through this account to customers.

**Comment by nivshah** [comment]
related to #2

**Comment by darthsmall** [comment]
account spun up - working out the emails

**Comment by nivshah** [comment]
@darthsmall http://kb.mailchimp.com/integrations/api-integrations/about-api-keys when you get a second

**Comment by darthsmall** [comment]
api key:
f9fc990956297a2682954ba5fd9ed76d-us16

**Comment by darthsmall** [comment]
mandrill setup notes: https://mandrillapp.com/settings/sending-domains

DKIM
DKIM is a DNS-based email authentication mechanism that helps Mandrill more effectively send mail on your behalf by allowing receivers to verify that we have permission to send your email. To enable DKIM, create a TXT record for mandrill._domainkey.yourdomain.com (just replace yourdomain.com with the domain you're setting up) with the following value:
v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB;
Some DNS providers require that semicolons be escaped. If your provider requires escaping, use this value instead:
v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrLHiExVd55zd/IQ/J/mRwSRMAocV/hMB3jXwaHH36d9NaVynQFYV8NaWi69c1veUtRzGt7yAioXqLj7Z4TeEUoOLgrKsn8YnckGs9i3B3tVFB+Ch/4mPhXWiNfNdynHWBcPcbJ8kjEQ2U8y78dHZj1YeRXXVvWob2OaKynO8/lQIDAQAB\;
SPF
SPF is another DNS-based email authentication mechanism. If you don't yet have an SPF record, you'll want to add one for your domain. At a minimum, the value should be the following if you're only sending mail through Mandrill for that domain:
v=spf1 include:spf.mandrillapp.com ?all

If you already have a TXT record with SPF information, you'll need to add Mandrill's servers to that record by adding include:spf.mandrillapp.com in the record (before the last operator, which is usually ?all, ~all, or -all).

**Comment by nivshah** [comment]
I've added DKIM and SPF records for moka.life. @darthsmall can you check if domain verification with mandrill is all set?

**Comment by darthsmall** [comment]
DKIM is good, SPF shows as missing

**Comment by darthsmall** [comment]
To enable SPF, create a TXT record for moka.life with the following value:

v=spf1 include:spf.mandrillapp.com ?all

**Comment by nivshah** [comment]
I have this record set up in Route 53 (AWS DNS)

<img width="1020" alt="screenshot 2017-07-12 11 00 52" src="https://user-images.githubusercontent.com/685145/28124358-6bf4fef0-66f1-11e7-8742-078954d7d384.png">

I have made this as a SPF record and not a TXT record since we already are using a TXT record for Google Domain verification. I'm wondering if as a SPF record maybe the value is different.

**Comment by nivshah** [comment]
I just did a DNS test from http://www.kitterman.com/spf/validate.html

```
Checking to see if there is a valid SPF record. 

Found v=spf1 record for moka.life: 
v=spf1 include:spf.mandrillapp.com ?all 

evaluating...
Results - record processed without error.
```

So maybe this is all fine

**Comment by darthsmall** [comment]
still throwing the same error for SPF

**Comment by nivshah** [comment]
Ok I changed the TXT record for moka.life

It now is:
```
"google-site-verification=DBzK8hX1OfU6osxCUpVOxp_oHjnGfyzDLLWi9n6jfKg; v=spf1 include:spf.mandrillapp.com ?all"
```
Maybe this will work?

**Comment by darthsmall** [comment]
<img width="934" alt="screen shot 2017-07-14 at 10 58 07 am" src="https://user-images.githubusercontent.com/28455051/28217524-5c85c54c-6883-11e7-9562-c5ca3957a77e.png">


v=spf1 google-site-verification=DBzK8hX1OfU6osxCUpVOxp_oHjnGfyzDLLWi9n6jfKg; include:spf.mandrillapp.com ?all

**Comment by nivshah** [comment]
Ha okay. Pretty awesome, Mailchimp.

I've updated the record to what Mailchimp requested.

**Comment by darthsmall** [comment]
Success!!!!!!!!!!!!!

**Comment by darthsmall** [comment]
api key: CVBYwU8F1PB7jBpKda9yxg
