### ISSUE TITLE
Add an About Us page

### ISSUE THREAD

**Issue by darthsmall** [ElCinco/moka#16]
same style as the FAQ page:

**Why we started Moka**
We believe that life insurance is the most important part of a good financial plan. Whether you have a policy or not can make the difference between poverty and wealth for generations. 
Our goal is to make it simple to get something so vitally important. We want to bring an entirely new perspective to buying life insurance. Our focus in on simplicity and transparency. We don’t believe in complicated products, aggressive sales people or confusing terminology.  
**Who we are**
Our team consists of experienced computer programmers, developers, designers and life insurance professionals. The only goal is to make buying life insurance easier, quicker and more understandable.  We use a combination of technology and design to help you get the protection that you need and making it quick and easy.
We are currently licensed in Virginia and Maryland with more states to come soon.

**Comment by darthsmall** [comment]
<img width="866" alt="screen shot 2017-07-10 at 9 15 07 pm" src="https://user-images.githubusercontent.com/28455051/28073233-24b47f58-6623-11e7-9b2d-1404ea1be12c.png">

**Comment by JFuller3000** [comment]
- [x] add about page to rails: route, action, view etc.
- [x]  add markup
- [x]  style it
- [x]  link to it in right rail when not on about page

**Comment by gearloan** [comment]
@darthsmall do you wanna change the header style to left justified everywhere?
