### ISSUE TITLE
come up with form confirmation message

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#19]
we need to figure out what the message a user sees after a clicking submit is.

as far as the front end we could replace the form content with whatever we want for a confirmation message

**Comment by JFuller3000** [comment]
Here's a starting point
_Button 1_
We'll check out your information and get back to you within 24hrs
_Button 2_
Your quote is in the works

**Comment by darthsmall** [comment]
those seem good to start with, can prob just add a Thank You. at the beginning

<img width="564" alt="screen shot 2017-07-12 at 3 50 46 pm" src="https://user-images.githubusercontent.com/28455051/28137092-096fe744-671a-11e7-9c37-cf2d03408de9.png">
