### ISSUE TITLE
setup email

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#2]
I guess we need to send two emails on submission of the form
 1. to john@mokalife with the customer data
 2. to the customer saying, 'thanks, we'll be back to you shortly; or something

When it comes to receiving email, I'm not sure how we want to deal with that. Hopefully you've got something up your sleeve

**Comment by nivshah** [comment]
@darthsmall can we spin up a help@moka.life or contact@moka.life alias?

Will use mailchimp to send out automated emails I believe.

**Comment by nivshah** [comment]
This is the gem we will want to use:

https://rubygems.org/gems/gibbon/versions/2.2.3

**Comment by darthsmall** [comment]
contact@moka.life is added as an alias for John

**Comment by nivshah** [comment]
We will not use gibbon - we need a Mandrill integration, not Mailchimp

https://rubygems.org/gems/mandrill-api/versions/1.0.53

**Comment by nivshah** [comment]
API key for Mandrill
```
CVBYwU8F1PB7jBpKda9yxg
```

per #14

**Comment by nivshah** [comment]
@darthsmall do we have email templates set up in Mandrill?

https://mandrill.zendesk.com/hc/en-us/articles/205583097-How-do-I-add-a-MailChimp-template-to-my-Mandrill-account-

**Comment by JFuller3000** [comment]
repeating what I said in the moka room:
now that product has become more solid I don't think we need to send automated emails anymore.

lemme know if that's wrong

**Comment by nivshah** [comment]
Closing this with WONTFIX for now.
