### ISSUE TITLE
Background image is currently placeholder

### ISSUE THREAD

**Issue by nivshah** [ElCinco/moka#3]
Should get the finalized background image, whatever it is, on the site

**Comment by JFuller3000** [comment]
i'm using a gradient overlay to make images of avg brightness work, so we don't have to stick with dark and slightly ominous images. unless we want to...

**Comment by darthsmall** [comment]
I like not using ominous images :) do you have enough to use?

**Comment by JFuller3000** [comment]
I don't. I only have that lego image

**Comment by JFuller3000** [comment]
these are up and we're loading one at random
