### ISSUE TITLE
add google analytics 

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#5]
we need to
- setup a google analytics account for jnjt?
- add tracking code to the site

Not sure how y'all want to handle the parent account for the google part?

**Comment by nivshah** [comment]
@darthsmall might make sense to spin up a JTJN google analytics org?

**Comment by JFuller3000** [comment]
this is all set, 
I'm using the rack-tracker gem to handle our various tracking scripts
https://github.com/railslove/rack-tracker
