### ISSUE TITLE
setup facebook pixel

### ISSUE THREAD

**Issue by JFuller3000** [ElCinco/moka#6]
- [x] add the pixel code to our site
- [ ] test it with their thing:
https://developers.facebook.com/docs/facebook-pixel/pixel-helper

**Comment by nivshah** [comment]
@gearloan what's going on with this mammajamma? what does this pixel get us? should this be a blocker to launching ads (should I add it to the 'launch ads' milestone?)

**Comment by JFuller3000** [comment]
hmm, i think you should ad it to the milestone. I was trying to be cute with it and now I'm just gonna add them a more  manual way. Shouldn't take long.
